### ISSUE TITLE
F14 conversion not working

### ISSUE THREAD

**Issue by PraetBen** [OP-TED/ted-xml-data-converter#12]
Dear,

I tried to run the conversion for F14 form. It does not work.

Will this be foreseen in the near future (and if so, when)?

Thank you

**Comment by pdonohoe** [comment]
Dear Sir, 

Apologies for the long delay in responding.

No, the converter will not work for F14 (Corrigendum) forms. It is not foreseen to convert F14 forms, because the location of changes is not indicated accurately enough in the XML to allow automatic conversion.
