### ISSUE TITLE
Missing F16, F17 and F18

### ISSUE THREAD

**Issue by thorbolo** [OP-TED/ted-xml-data-converter#13]
Hi there,

F16, F17 and F18 were never released under R209, but in the old R208.

Will there be any migrations for them?

**Comment by pdonohoe** [comment]
Dear Sir,

Thank you for your question, and apologies for the long delay in responding.

Yes, work has started on conversion of the R208 forms. Conversion of form F16 (PIN) will be included in the converter in the release after the next release. Work will start on the F17 and F18 forms after this.
