### ISSUE TITLE
Support for contract modification notices (F20)

### ISSUE THREAD

**Issue by maximAtanasov** [OP-TED/ted-xml-data-converter#14]
Hello, 
is support for these notices planned?

**Comment by pdonohoe** [comment]
Dear Sir,

Thank you for your question, and apologies for the long delay in responding.

Conversion of F20 (Contract Modification) forms has not yet been considered. The details of changes seem to be more identifiable in the XML than in F14 forms. If conversion is indeed possible, work on them will be scheduled to follow the Defence forms.
