### ISSUE TITLE
Unable to convert document 

### ISSUE THREAD

**Issue by poetsmeniet** [OP-TED/ted-xml-data-converter#28]
Hi,

Using the latest version of the converter, with Saxon12.

I'm having an issue with conversion of a document with version R2.0.9.S05.E01. I get the following error message:

```
ERROR: found 0 different form types in 
Error on line 61 column 32 of ted-to-eforms.xslt:
  XTMM9000  Processing terminated by xsl:message at line 61 in ted-to-eforms.xslt
  In template rule with match="/" on line 58 of ted-to-eforms.xslt
Processing terminated by xsl:message at line 61 in ted-to-eforms.xslt
```

Specifically document 2023-OJS124-00394125.xml

Please advise,

Cheers,
Thomas

**Comment by poetsmeniet** [comment]
@pdonohoe Hi Paul, is there any progress being made on this one?

**Comment by pdonohoe** [comment]
Hi @poetsmeniet , sorry I was on annual leave. I am not able to replicate this error, I can successfully convert this notice using the converter API, and also convert and import it into "My notices" in eNotices2. Can you please check again, and if you get the error again, let me know which service you are using to convert it?

**Comment by poetsmeniet** [comment]
Hi Paul, no problem. I think I forgot to update the repo, or maybe was working in an old project folder. The file converts fine now.

Thanks
